name: RequestedAndCompleted

on:
  workflow_run:
    workflows:
      - Azure Static Web Apps CI/CD
    types:
      - requested
      - completed

jobs:
  on-requested:
    name: On Requested
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == '' }}
    steps:
      - run: echo 'The triggering requested'
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
