name: Run job and notify failure to Slack
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Random exit
        run: exit $(($RANDOM%2))
      - name: Notify slack when job failed
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: "C049R06CHNX"
          payload: |
            {
              "text": "失敗しました",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "buildが失敗しました\ngithub: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
